[classification]
# Models are described in the repo: https://github.com/fschmid56/EfficientAT?tab=readme-ov-file#pre-trained-models
# Select one of the following models: dymn04_as, dymn10_as, dymn20_as, mn04_as, mn05_as, mn10_as, mn20_as, mn30_as, mn40_as, mn40_as_ext
# If ensemble is empty, the model_name will be used as the single model.
# If ensemble is specified, it should be a comma-separated list of model names.
model_name=mn40_as
ensemble=
debug_mode=False

[influx2]
url=
org=
token=
log_bucket=none
data_bucket=
delay=
